<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_firstName</name>
   <tag></tag>
   <elementGuidId>de56a5e1-4aec-4eef-891e-7da70be606ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b10b4192-191d-419d-bc6a-f66ffe375ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>f6f1a408-6f5c-4e64-baf2-a7cd3195ae99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>da0feaf0-5bdb-4a16-a688-f9004d0c0718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstName&quot;)</value>
      <webElementGuid>23641f05-28f1-4f50-8069-d2a87128b72e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstName']</value>
      <webElementGuid>d6edc483-32a5-4675-8e86-80ddb4d71e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-contact']/p/input</value>
      <webElementGuid>262c711d-11a8-4c5a-9008-199ad4a64af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aef8e8a5-10de-4ead-b551-139dc4e4d0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'firstName' and @placeholder = 'First Name']</value>
      <webElementGuid>714afedf-c135-4b07-bda6-bd043346672e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
