<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address 2_street2</name>
   <tag></tag>
   <elementGuidId>7ac43d22-c511-4d30-ac9a-17cfc3ec7f43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#street2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='street2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c123a27b-28ac-458f-9488-12beca3b2f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>street2</value>
      <webElementGuid>2fdbfd49-325b-4888-9d62-48da1e06fb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 2</value>
      <webElementGuid>2f099e29-a456-44b1-823c-0b426d817fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street2&quot;)</value>
      <webElementGuid>4121011e-d65b-4104-b1cc-c9adb6d86757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='street2']</value>
      <webElementGuid>6a05bbef-08bd-43bc-a013-f4718e6689e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-contact']/p[5]/input</value>
      <webElementGuid>37b6fa3f-e5a3-457c-a1c2-4022f3d403b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>3ef2b24c-5557-4457-b883-1c5840ec713a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'street2' and @placeholder = 'Address 2']</value>
      <webElementGuid>fd3357f2-437e-4556-864e-2ab08ea76d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
