<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address 1_street1</name>
   <tag></tag>
   <elementGuidId>2d46af53-3e98-494e-81ba-a65f7cc35731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#street1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='street1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1a98eeb-8b13-44db-a927-defe3017e65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>street1</value>
      <webElementGuid>bfe71682-fa7b-4b70-b095-ca4540a1bc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 1</value>
      <webElementGuid>5a716ed7-e9e0-44a1-8cee-5f33bcd2bd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street1&quot;)</value>
      <webElementGuid>cb5bcddd-c0de-496c-8434-45a03753c3f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='street1']</value>
      <webElementGuid>b5249e28-e0b9-4162-8de7-584abcbd37ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-contact']/p[4]/input</value>
      <webElementGuid>f3d38a70-8847-4841-a230-15ce43792170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>e4d7e09c-019a-4f0c-bd0f-ae35fca7bff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'street1' and @placeholder = 'Address 1']</value>
      <webElementGuid>1f20da96-1e7b-4525-a128-022273898c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
